[default]
# Set through env variable if preferred:
# ROCKET_UPLOAD_DIR=<path>
upload_dir = "./upload"

# Allow bigger uploads
limits.file = "50MiB"
limits.data-form = "51MiB"

[default.databases.sea_orm]
# Set through env variable if preferred:
# ROCKET_DATABASES='{sea_orm={url="postgresql://localhost/metatv"}}'
url = "postgres://root:root@localhost/metatv"

[default.oidc]
# Set through env variable if preferred:
# ROCKET_OIDC='{issuer_url="postgresql://localhost/metatv",client_id="",client_secret="",redirect_url="http://localhost:5000/auth/oidc-callback"}'
issuer_url = "https://example.com"
client_id = ""
client_secret = ""
redirect_url = "http://localhost:5000/auth/oidc-callback"
