//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::content::Entity as Content;
pub use super::screen::Entity as Screen;
pub use super::slide::Entity as Slide;
pub use super::slide_group::Entity as SlideGroup;
