//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "slide_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub priority: i32,
    pub hidden: bool,
    pub created_by: String,
    pub start_date: DateTime,
    pub end_date: Option<DateTime>,
    pub archive_date: Option<DateTime>,
    pub published: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::slide::Entity")]
    Slide,
}

impl Related<super::slide::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slide.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
