[package]
name = "frontend"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common", features = ["entity"] }
leptos = { version = "0.8.0-beta", features = ["csr"] }
leptos_meta = { version = "0.8.0-beta" }
leptos_router = { version = "0.8.0-beta" }
console_log = "1"
log = "0.4"
console_error_panic_hook = "0.1"
gloo-net = "0.6.0"
thiserror = "2.0.12"
chrono = "0.4.40"
web-sys = { version = "0.3", features = ["Blob", "File", "FileList", "FormData", "HtmlInputElement"] }
serde_json = "1.0.140"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = { version = "0.3", features = ["Document", "Window"] }
