[package]
name = "meta-tv-rs"
version.workspace = true
edition.workspace = true
default-run = "meta-tv-rs"

[dependencies]
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["ws"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
